site_name: HOUARI Abdelmouhssine's Documentation
site_name: Documentation
site_url: https://doc.ahouari-tech.fr 
site_description: un Site web qui décrit tous les nouveautés du DevOps 
site_author: HOUARI ABDELMOUHSSINE
dev_addr: 192.168.0.1:8000
repo_url: https://github.com/HOUARIMouhssine/LAB.git

theme:
  #name: mkdocs
  #locale: fr
  #analytics: {gtag: 'G-274394082'}
  #highlightjs: true
  #hljs_languages:
  #  - yaml
  #  - django
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
nav:
  - Home: index.md
  - Documentation: doc.md
  - DNS: dns.md
  - Virtualbox: vbox.md
  - Vagrant: vagrant.md 
  - NFS: nfs.md 
  - ROOK: rook-ceph.md 
    #extra_css:
    #- css/extra.css

